apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  CONTENTFUL_ACCESS_TOKEN: {{ .Values.contentful.access_token }}
  CONTENTFUL_SPACE_ID: {{ .Values.contentful.space_id }}
  CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: {{ .Values.contentful.management_access_token }}
