#!/bin/sh

kubectl delete secret --namespace $CLUSTER_NAMESPACE ikenom-gh-reg

kubectl create secret docker-registry ikenom-gh-reg \
    --docker-username=$DOCKER_USERNAME \
    --docker-password=$DOCKER_PASSWORD \
    --docker-server=$SERVER \
    --namespace $CLUSTER_NAMESPACE

helm repo add bitnami https://charts.bitnami.com/bitnami